runtime: python27
api_version: 1
service: projectx
threadsafe: true

handlers:
- url: /ui/dashboard
  static_files: ui/dashboard.html
  upload: ui/dashboard.html
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0

- url: /ui
  static_dir: ui/
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0

- url: /ping
  script: starter.scheduler
- url: /work
  script: starter.worker
- url: /manager/.*
  script: starter.taskmanager