runtime: python27
api_version: 1
service: projectx
threadsafe: true

handlers:
- url: /assets
  static_dir: ui/assets

- url: /ping
  script: starter.scheduler
- url: /work
  script: starter.worker
- url: /manager/.*
  script: starter.taskmanager
- url: /dashboard
  script: starter.uirouter
